# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 1

[[main]]
  name = "Team"
  identifier = "authors"
  URL = "#"
  weight = 2.0

[[main]]
  name = "Laura Vandenbosch"
  parent = "authors"
  url = "/authors/admin1"
  weight = 2.1
  
[[main]]
  name = "Anaëlle Gonzalez"
  parent = "authors"
  url = "/authors/admin2"
  weight = 2.2

[[main]]
  name = "Brent Swinnen"
  parent = "authors"
  url = "/authors/admin3"
  weight = 2.3

[[main]]
  name = "Luca Carbone"
  parent = "authors"
  url = "/authors/admin4"
  weight = 2.4

[[main]]
  name = "Bojana Lobe"
  parent = "authors"
  url = "/authors/admin10"
  weight = 2.5

[[main]]
  name = "Caroline Giraudeau"
  parent = "authors"
  url = "/authors/admin11"
  weight = 2.6

[[main]]
  name = "Resources"
  identifier = "resources"
  url = "#"
  weight = 3.0

[[main]]
  name = "Academic Output"
  parent = "resources"
  url = "#academic_output"
  weight = 3.1

[[main]]
  name = "Open science"
  parent = "resources"
  url = "/open_science"
  weight = 3.2

[[main]]
  name = "Schools"
  identifier = "schools"
  url = "#"
  weight = 4.0

[[main]]
  name = "List of participating schools"
  parent = "schools"
  url = "/list"
  weight = 4.1

[[main]]
  name = "Additional information"
  parent = "schools"
  url = "/additional"
  weight = 4.2

[[main]]
  name = "Parent and Adolescents"
  identifier = "parents_adolescents"
  url = "#"
  weight = 5.0

[[main]]
  name = "For Parents"
  parent = "parents_adolescents"
  url = "/parents"
  weight = 5.1

[[main]]
  name = "For Adolescents"
  parent = "parents_adolescents"
  url = "/adolescents"
  weight = 5.2

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 6

[[main_right]]
    name = "<img src=\"/img/logo.png\" style=\"height:50px\" alt=\"ERC\">"

