# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 1

[[main]]
  name = "Team"
  identifier = "authors"
  URL = "#"
  weight = 2.0

[[main]]
  name = "Laura Vandenbosch"
  parent = "authors"
  url = "/authors/1admin1"
  weight = 2.1
  
[[main]]
  name = "Anaëlle Gonzalez"
  parent = "authors"
  url = "/authors/1admin2"
  weight = 2.2

[[main]]
  name = "Gaëlle Vanhoffelen"
  parent = "authors"
  url = "/authors/1admin3"
  weight = 2.3

[[main]]
  name = "Luca Carbone"
  parent = "authors"
  url = "/authors/1admin4"
  weight = 2.4

[[main]]
  name = "Jasmina Rosič"
  parent = "authors"
  url = "/authors/1admin5"
  weight = 2.5

[[main]]
  name = "Kaitlin Fitzgerald"
  parent = "authors"
  url = "/authors/1admin6"
  weight = 2.6

[[main]]
  name = "Bojana Lobe"
  parent = "authors"
  url = "/authors/4clb_user10"
  weight = 2.7

[[main]]
  name = "Caroline Giraudeau"
  parent = "authors"
  url = "/authors/4clb_user11"
  weight = 2.8

[[main]]
  name = "Kristina Rakinić"
  parent = "authors"
  url = "/authors/4clb_user13"
  weight = 2.9

[[main]]
  name = "Resources"
  identifier = "resources"
  url = "#"
  weight = 3.0

[[main]]
  name = "Academic Output"
  parent = "resources"
  url = "#academic_output"
  weight = 3.1

[[main]]
  name = "Debriefings"
  parent = "resources"
  url = "#debriefings"
  weight = 3.2

[[main]]
  name = "Open science"
  parent = "resources"
  url = "/open_science"
  weight = 3.3

[[main]]
  name = "Videos"
  parent = "resources"
  url = "/videos"
  weight = 3.4

[[main]]
  name = "Schools"
  identifier = "schools"
  url = "#"
  weight = 4.0

[[main]]
  name = "List of participating schools"
  parent = "schools"
  url = "/list"
  weight = 4.1

[[main]]
  name = "Media Literate Schools"
  parent = "schools"
  url = "/media_lit_schools"
  weight = 4.2

[[main]]
  name = "Parents and Participants"
  identifier = "parents_adolescents"
  url = "#"
  weight = 5.0

[[main]]
  name = "For Parents"
  parent = "parents_adolescents"
  url = "/parents"
  weight = 5.1

[[main]]
  name = "For Participants"
  parent = "parents_adolescents"
  url = "/adolescents"
  weight = 5.2

[[main]]
  name = "News"
  url = "/news"
  weight = 6

[[main]]
  name = "Social Media & Press"
  url = "/social"
  weight = 7

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 8

# [[main_right]]
#  name = "<img src=\"/img/logo.png\" style=\"height:50px\" alt=\"ERC\">"