---
authors:
- admin1
bio:
education:
  courses:
  - course: PhD in communicatiewetenschap
    institution: Katholieke Universiteit Leuven
    year: 2013
email: ""
interests:
- Mediapsychologie
- Adolescenten
- De jongvolwassenheid
- Welzijn
- Seksuele rijping
- Mediageletterdheid
- Vervormbaarheid
name: Laura Vandenbosch
organizations:
- name: KU Leuven
  url: "https://soc.kuleuven.be/smc/staff/00060068"
role: Universitair docent aan de School for Mass Communication Research
social:
- icon: envelope
  icon_pack: fas
  link: 'laura.vandenbosch@kuleuven.be'
- icon: twitter
  icon_pack: fab
  link: https://twitter.com/l__vandenbosch
- icon: google-scholar
  icon_pack: ai
  link: https://scholar.google.com/citations?hl=en&user=damaWSwAAAAJ&view_op=list_works&citft=1&email_for_op=LucaCarbone.LC%40gmail.com&gmla=AJsN-F7t2CYHHlWeJY3deewm-X4ZMmGIyZTX8n6I4B0oyaPhiurr6O2RUvipMX5kj9NwSv5kCHA2iTvFV4Mkw7GA0m9U2mBQIWHnywgqOTMUu29QbimAgPW-k6oqxRFTvedMc-D8SrQc4AFyq6LA87ar4PJhZDpsA_B1-Z4uS742VbL1rEjrScyqh32yVBuYH_9IQXpNhLYqxWzdcpTOOOCxzpH6y9I_rk1ygE4T84JbQJD0nAO6CnsJZ1xjg5s4r59O_87gwvRR
- icon: orcid
  icon_pack: ai ai-orcid
  link: https://orcid.org/0000-0001-6834-8386
superuser: true
user_groups:
- Team
---

Laura Vandenbosch is sinds 2017 universitair docent aan de School for Mass Communication Research (BOF-ZAP Research Professororship Grant). De relatie tussen media en welzijn is het kernonderwerp van haar onderzoek en heeft geleid tot internationale publicaties op verschillende gebieden, waaronder ontwikkelingspsychologie, seksuologie, lichaamsbeeld, sociale relaties en communicatietheorie.

In 2015 werd ze verkozen tot secretaris van de afdeling Kinderen, Adolescenten en Media van de International Communication Association (2015-2018). Laura is momenteel ook redactielid van ISI-gerangschikte tijdschriften Human Communication Research, Journal of Children and Media en Communications: The European Journal of Communication Research.

Momenteel is ze betrokken bij verschillende (internationale) onderzoeksprojecten om te onderzoeken hoe media het welzijn kunnen beïnvloeden door zich te concentreren op factoren die niet goed zijn begrepen, zoals de rol van sociale relaties, culturele achtergrond, seksualisering, mediageletterdheid en maakbaarheid. overtuigingen. Een deel van deze projecten is ingebed in het internationale netwerk dat ze door de jaren heen heeft opgebouwd door periodes in het buitenland door te brengen, bijvoorbeeld in de U van Michigan, de U van Toronto en de U van Wenen. Haar werk heeft geleid tot verschillende prijzen, zoals de Top Paper, Top Article en Top Dissertation Awards van de Children, Adolescents and Media (CAM) Division van de International Communication Association (2013-2016) en de Research Council Award in the Humanities (Prijs Onderzoeksraad, 2016).

In 2019 ontving ze een ERC-startsubsidie voor het project 'Smeedbaarheid in gemedieerde idealen: een paradigma om de effecten van hedendaagse media op het welzijn van adolescenten te begrijpen'.